[package]
name = "mock_tokens"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.17"
serde = { version = "1.0.219", features = ["derive"] }
